######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 30 21:18:11 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainWindow.h
SOURCES += main.cc mainWindow.cc
RESOURCES += resources.qrc
