// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book.proto

#ifndef PROTOBUF_book_2eproto__INCLUDED
#define PROTOBUF_book_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace book {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_book_2eproto();
void protobuf_AssignDesc_book_2eproto();
void protobuf_ShutdownFile_book_2eproto();

class BasicDataTable;
class IndexDataMapTable;
class IndexDataMapTable_IndexDataMapPair;
class ModeTable;
class ModeTable_CodeIndexMapPair;
class Node;
class NodeTree;
class book;

enum book_ModeType {
  book_ModeType_GAME = 0,
  book_ModeType_STUDY = 1,
  book_ModeType_STORY = 2
};
bool book_ModeType_IsValid(int value);
const book_ModeType book_ModeType_ModeType_MIN = book_ModeType_GAME;
const book_ModeType book_ModeType_ModeType_MAX = book_ModeType_STORY;
const int book_ModeType_ModeType_ARRAYSIZE = book_ModeType_ModeType_MAX + 1;

const ::google::protobuf::EnumDescriptor* book_ModeType_descriptor();
inline const ::std::string& book_ModeType_Name(book_ModeType value) {
  return ::google::protobuf::internal::NameOfEnum(
    book_ModeType_descriptor(), value);
}
inline bool book_ModeType_Parse(
    const ::std::string& name, book_ModeType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<book_ModeType>(
    book_ModeType_descriptor(), name, value);
}
// ===================================================================

class BasicDataTable : public ::google::protobuf::Message {
 public:
  BasicDataTable();
  virtual ~BasicDataTable();

  BasicDataTable(const BasicDataTable& from);

  inline BasicDataTable& operator=(const BasicDataTable& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BasicDataTable& default_instance();

  void Swap(BasicDataTable* other);

  // implements Message ----------------------------------------------

  inline BasicDataTable* New() const { return New(NULL); }

  BasicDataTable* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BasicDataTable& from);
  void MergeFrom(const BasicDataTable& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BasicDataTable* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated bytes audioData = 1;
  inline int audiodata_size() const;
  inline void clear_audiodata();
  static const int kAudioDataFieldNumber = 1;
  inline const ::std::string& audiodata(int index) const;
  inline ::std::string* mutable_audiodata(int index);
  inline void set_audiodata(int index, const ::std::string& value);
  inline void set_audiodata(int index, const char* value);
  inline void set_audiodata(int index, const void* value, size_t size);
  inline ::std::string* add_audiodata();
  inline void add_audiodata(const ::std::string& value);
  inline void add_audiodata(const char* value);
  inline void add_audiodata(const void* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& audiodata() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_audiodata();

  // @@protoc_insertion_point(class_scope:book.BasicDataTable)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> audiodata_;
  friend void  protobuf_AddDesc_book_2eproto();
  friend void protobuf_AssignDesc_book_2eproto();
  friend void protobuf_ShutdownFile_book_2eproto();

  void InitAsDefaultInstance();
  static BasicDataTable* default_instance_;
};
// -------------------------------------------------------------------

class IndexDataMapTable_IndexDataMapPair : public ::google::protobuf::Message {
 public:
  IndexDataMapTable_IndexDataMapPair();
  virtual ~IndexDataMapTable_IndexDataMapPair();

  IndexDataMapTable_IndexDataMapPair(const IndexDataMapTable_IndexDataMapPair& from);

  inline IndexDataMapTable_IndexDataMapPair& operator=(const IndexDataMapTable_IndexDataMapPair& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const IndexDataMapTable_IndexDataMapPair& default_instance();

  void Swap(IndexDataMapTable_IndexDataMapPair* other);

  // implements Message ----------------------------------------------

  inline IndexDataMapTable_IndexDataMapPair* New() const { return New(NULL); }

  IndexDataMapTable_IndexDataMapPair* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const IndexDataMapTable_IndexDataMapPair& from);
  void MergeFrom(const IndexDataMapTable_IndexDataMapPair& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(IndexDataMapTable_IndexDataMapPair* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 index = 1;
  inline bool has_index() const;
  inline void clear_index();
  static const int kIndexFieldNumber = 1;
  inline ::google::protobuf::int32 index() const;
  inline void set_index(::google::protobuf::int32 value);

  // required int32 offset = 2;
  inline bool has_offset() const;
  inline void clear_offset();
  static const int kOffsetFieldNumber = 2;
  inline ::google::protobuf::int32 offset() const;
  inline void set_offset(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:book.IndexDataMapTable.IndexDataMapPair)
 private:
  inline void set_has_index();
  inline void clear_has_index();
  inline void set_has_offset();
  inline void clear_has_offset();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 index_;
  ::google::protobuf::int32 offset_;
  friend void  protobuf_AddDesc_book_2eproto();
  friend void protobuf_AssignDesc_book_2eproto();
  friend void protobuf_ShutdownFile_book_2eproto();

  void InitAsDefaultInstance();
  static IndexDataMapTable_IndexDataMapPair* default_instance_;
};
// -------------------------------------------------------------------

class IndexDataMapTable : public ::google::protobuf::Message {
 public:
  IndexDataMapTable();
  virtual ~IndexDataMapTable();

  IndexDataMapTable(const IndexDataMapTable& from);

  inline IndexDataMapTable& operator=(const IndexDataMapTable& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const IndexDataMapTable& default_instance();

  void Swap(IndexDataMapTable* other);

  // implements Message ----------------------------------------------

  inline IndexDataMapTable* New() const { return New(NULL); }

  IndexDataMapTable* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const IndexDataMapTable& from);
  void MergeFrom(const IndexDataMapTable& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(IndexDataMapTable* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef IndexDataMapTable_IndexDataMapPair IndexDataMapPair;

  // accessors -------------------------------------------------------

  // required .book.IndexDataMapTable.IndexDataMapPair indexDataMapPair = 1;
  inline bool has_indexdatamappair() const;
  inline void clear_indexdatamappair();
  static const int kIndexDataMapPairFieldNumber = 1;
  inline const ::book::IndexDataMapTable_IndexDataMapPair& indexdatamappair() const;
  inline ::book::IndexDataMapTable_IndexDataMapPair* mutable_indexdatamappair();
  inline ::book::IndexDataMapTable_IndexDataMapPair* release_indexdatamappair();
  inline void set_allocated_indexdatamappair(::book::IndexDataMapTable_IndexDataMapPair* indexdatamappair);

  // @@protoc_insertion_point(class_scope:book.IndexDataMapTable)
 private:
  inline void set_has_indexdatamappair();
  inline void clear_has_indexdatamappair();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::book::IndexDataMapTable_IndexDataMapPair* indexdatamappair_;
  friend void  protobuf_AddDesc_book_2eproto();
  friend void protobuf_AssignDesc_book_2eproto();
  friend void protobuf_ShutdownFile_book_2eproto();

  void InitAsDefaultInstance();
  static IndexDataMapTable* default_instance_;
};
// -------------------------------------------------------------------

class ModeTable_CodeIndexMapPair : public ::google::protobuf::Message {
 public:
  ModeTable_CodeIndexMapPair();
  virtual ~ModeTable_CodeIndexMapPair();

  ModeTable_CodeIndexMapPair(const ModeTable_CodeIndexMapPair& from);

  inline ModeTable_CodeIndexMapPair& operator=(const ModeTable_CodeIndexMapPair& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ModeTable_CodeIndexMapPair& default_instance();

  void Swap(ModeTable_CodeIndexMapPair* other);

  // implements Message ----------------------------------------------

  inline ModeTable_CodeIndexMapPair* New() const { return New(NULL); }

  ModeTable_CodeIndexMapPair* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ModeTable_CodeIndexMapPair& from);
  void MergeFrom(const ModeTable_CodeIndexMapPair& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ModeTable_CodeIndexMapPair* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 code = 1;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 1;
  inline ::google::protobuf::int32 code() const;
  inline void set_code(::google::protobuf::int32 value);

  // repeated int32 indexList = 2;
  inline int indexlist_size() const;
  inline void clear_indexlist();
  static const int kIndexListFieldNumber = 2;
  inline ::google::protobuf::int32 indexlist(int index) const;
  inline void set_indexlist(int index, ::google::protobuf::int32 value);
  inline void add_indexlist(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      indexlist() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_indexlist();

  // @@protoc_insertion_point(class_scope:book.ModeTable.CodeIndexMapPair)
 private:
  inline void set_has_code();
  inline void clear_has_code();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > indexlist_;
  ::google::protobuf::int32 code_;
  friend void  protobuf_AddDesc_book_2eproto();
  friend void protobuf_AssignDesc_book_2eproto();
  friend void protobuf_ShutdownFile_book_2eproto();

  void InitAsDefaultInstance();
  static ModeTable_CodeIndexMapPair* default_instance_;
};
// -------------------------------------------------------------------

class ModeTable : public ::google::protobuf::Message {
 public:
  ModeTable();
  virtual ~ModeTable();

  ModeTable(const ModeTable& from);

  inline ModeTable& operator=(const ModeTable& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ModeTable& default_instance();

  void Swap(ModeTable* other);

  // implements Message ----------------------------------------------

  inline ModeTable* New() const { return New(NULL); }

  ModeTable* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ModeTable& from);
  void MergeFrom(const ModeTable& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ModeTable* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ModeTable_CodeIndexMapPair CodeIndexMapPair;

  // accessors -------------------------------------------------------

  // repeated .book.ModeTable.CodeIndexMapPair codeIndexMapPair = 1;
  inline int codeindexmappair_size() const;
  inline void clear_codeindexmappair();
  static const int kCodeIndexMapPairFieldNumber = 1;
  inline const ::book::ModeTable_CodeIndexMapPair& codeindexmappair(int index) const;
  inline ::book::ModeTable_CodeIndexMapPair* mutable_codeindexmappair(int index);
  inline ::book::ModeTable_CodeIndexMapPair* add_codeindexmappair();
  inline const ::google::protobuf::RepeatedPtrField< ::book::ModeTable_CodeIndexMapPair >&
      codeindexmappair() const;
  inline ::google::protobuf::RepeatedPtrField< ::book::ModeTable_CodeIndexMapPair >*
      mutable_codeindexmappair();

  // @@protoc_insertion_point(class_scope:book.ModeTable)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::book::ModeTable_CodeIndexMapPair > codeindexmappair_;
  friend void  protobuf_AddDesc_book_2eproto();
  friend void protobuf_AssignDesc_book_2eproto();
  friend void protobuf_ShutdownFile_book_2eproto();

  void InitAsDefaultInstance();
  static ModeTable* default_instance_;
};
// -------------------------------------------------------------------

class Node : public ::google::protobuf::Message {
 public:
  Node();
  virtual ~Node();

  Node(const Node& from);

  inline Node& operator=(const Node& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Node& default_instance();

  void Swap(Node* other);

  // implements Message ----------------------------------------------

  inline Node* New() const { return New(NULL); }

  Node* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Node& from);
  void MergeFrom(const Node& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Node* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 startCode = 1;
  inline bool has_startcode() const;
  inline void clear_startcode();
  static const int kStartCodeFieldNumber = 1;
  inline ::google::protobuf::int32 startcode() const;
  inline void set_startcode(::google::protobuf::int32 value);

  // required int32 endCode = 2;
  inline bool has_endcode() const;
  inline void clear_endcode();
  static const int kEndCodeFieldNumber = 2;
  inline ::google::protobuf::int32 endcode() const;
  inline void set_endcode(::google::protobuf::int32 value);

  // required int32 previous = 3;
  inline bool has_previous() const;
  inline void clear_previous();
  static const int kPreviousFieldNumber = 3;
  inline ::google::protobuf::int32 previous() const;
  inline void set_previous(::google::protobuf::int32 value);

  // repeated int32 next = 4;
  inline int next_size() const;
  inline void clear_next();
  static const int kNextFieldNumber = 4;
  inline ::google::protobuf::int32 next(int index) const;
  inline void set_next(int index, ::google::protobuf::int32 value);
  inline void add_next(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      next() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_next();

  // repeated int32 defaultCode = 5;
  inline int defaultcode_size() const;
  inline void clear_defaultcode();
  static const int kDefaultCodeFieldNumber = 5;
  inline ::google::protobuf::int32 defaultcode(int index) const;
  inline void set_defaultcode(int index, ::google::protobuf::int32 value);
  inline void add_defaultcode(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      defaultcode() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_defaultcode();

  // @@protoc_insertion_point(class_scope:book.Node)
 private:
  inline void set_has_startcode();
  inline void clear_has_startcode();
  inline void set_has_endcode();
  inline void clear_has_endcode();
  inline void set_has_previous();
  inline void clear_has_previous();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 startcode_;
  ::google::protobuf::int32 endcode_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > next_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > defaultcode_;
  ::google::protobuf::int32 previous_;
  friend void  protobuf_AddDesc_book_2eproto();
  friend void protobuf_AssignDesc_book_2eproto();
  friend void protobuf_ShutdownFile_book_2eproto();

  void InitAsDefaultInstance();
  static Node* default_instance_;
};
// -------------------------------------------------------------------

class NodeTree : public ::google::protobuf::Message {
 public:
  NodeTree();
  virtual ~NodeTree();

  NodeTree(const NodeTree& from);

  inline NodeTree& operator=(const NodeTree& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NodeTree& default_instance();

  void Swap(NodeTree* other);

  // implements Message ----------------------------------------------

  inline NodeTree* New() const { return New(NULL); }

  NodeTree* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const NodeTree& from);
  void MergeFrom(const NodeTree& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(NodeTree* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .book.Node treeNode = 1;
  inline int treenode_size() const;
  inline void clear_treenode();
  static const int kTreeNodeFieldNumber = 1;
  inline const ::book::Node& treenode(int index) const;
  inline ::book::Node* mutable_treenode(int index);
  inline ::book::Node* add_treenode();
  inline const ::google::protobuf::RepeatedPtrField< ::book::Node >&
      treenode() const;
  inline ::google::protobuf::RepeatedPtrField< ::book::Node >*
      mutable_treenode();

  // @@protoc_insertion_point(class_scope:book.NodeTree)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::book::Node > treenode_;
  friend void  protobuf_AddDesc_book_2eproto();
  friend void protobuf_AssignDesc_book_2eproto();
  friend void protobuf_ShutdownFile_book_2eproto();

  void InitAsDefaultInstance();
  static NodeTree* default_instance_;
};
// -------------------------------------------------------------------

class book : public ::google::protobuf::Message {
 public:
  book();
  virtual ~book();

  book(const book& from);

  inline book& operator=(const book& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const book& default_instance();

  void Swap(book* other);

  // implements Message ----------------------------------------------

  inline book* New() const { return New(NULL); }

  book* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const book& from);
  void MergeFrom(const book& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(book* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef book_ModeType ModeType;
  static const ModeType GAME = book_ModeType_GAME;
  static const ModeType STUDY = book_ModeType_STUDY;
  static const ModeType STORY = book_ModeType_STORY;
  static inline bool ModeType_IsValid(int value) {
    return book_ModeType_IsValid(value);
  }
  static const ModeType ModeType_MIN =
    book_ModeType_ModeType_MIN;
  static const ModeType ModeType_MAX =
    book_ModeType_ModeType_MAX;
  static const int ModeType_ARRAYSIZE =
    book_ModeType_ModeType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ModeType_descriptor() {
    return book_ModeType_descriptor();
  }
  static inline const ::std::string& ModeType_Name(ModeType value) {
    return book_ModeType_Name(value);
  }
  static inline bool ModeType_Parse(const ::std::string& name,
      ModeType* value) {
    return book_ModeType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .book.NodeTree nodeTree = 1;
  inline bool has_nodetree() const;
  inline void clear_nodetree();
  static const int kNodeTreeFieldNumber = 1;
  inline const ::book::NodeTree& nodetree() const;
  inline ::book::NodeTree* mutable_nodetree();
  inline ::book::NodeTree* release_nodetree();
  inline void set_allocated_nodetree(::book::NodeTree* nodetree);

  // repeated .book.ModeTable modeTabelList = 2;
  inline int modetabellist_size() const;
  inline void clear_modetabellist();
  static const int kModeTabelListFieldNumber = 2;
  inline const ::book::ModeTable& modetabellist(int index) const;
  inline ::book::ModeTable* mutable_modetabellist(int index);
  inline ::book::ModeTable* add_modetabellist();
  inline const ::google::protobuf::RepeatedPtrField< ::book::ModeTable >&
      modetabellist() const;
  inline ::google::protobuf::RepeatedPtrField< ::book::ModeTable >*
      mutable_modetabellist();

  // required .book.book.ModeType curMode = 3 [default = STUDY];
  inline bool has_curmode() const;
  inline void clear_curmode();
  static const int kCurModeFieldNumber = 3;
  inline ::book::book_ModeType curmode() const;
  inline void set_curmode(::book::book_ModeType value);

  // @@protoc_insertion_point(class_scope:book.book)
 private:
  inline void set_has_nodetree();
  inline void clear_has_nodetree();
  inline void set_has_curmode();
  inline void clear_has_curmode();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::book::NodeTree* nodetree_;
  ::google::protobuf::RepeatedPtrField< ::book::ModeTable > modetabellist_;
  int curmode_;
  friend void  protobuf_AddDesc_book_2eproto();
  friend void protobuf_AssignDesc_book_2eproto();
  friend void protobuf_ShutdownFile_book_2eproto();

  void InitAsDefaultInstance();
  static book* default_instance_;
};
// ===================================================================


// ===================================================================

// BasicDataTable

// repeated bytes audioData = 1;
inline int BasicDataTable::audiodata_size() const {
  return audiodata_.size();
}
inline void BasicDataTable::clear_audiodata() {
  audiodata_.Clear();
}
inline const ::std::string& BasicDataTable::audiodata(int index) const {
  // @@protoc_insertion_point(field_get:book.BasicDataTable.audioData)
  return audiodata_.Get(index);
}
inline ::std::string* BasicDataTable::mutable_audiodata(int index) {
  // @@protoc_insertion_point(field_mutable:book.BasicDataTable.audioData)
  return audiodata_.Mutable(index);
}
inline void BasicDataTable::set_audiodata(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:book.BasicDataTable.audioData)
  audiodata_.Mutable(index)->assign(value);
}
inline void BasicDataTable::set_audiodata(int index, const char* value) {
  audiodata_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:book.BasicDataTable.audioData)
}
inline void BasicDataTable::set_audiodata(int index, const void* value, size_t size) {
  audiodata_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:book.BasicDataTable.audioData)
}
inline ::std::string* BasicDataTable::add_audiodata() {
  return audiodata_.Add();
}
inline void BasicDataTable::add_audiodata(const ::std::string& value) {
  audiodata_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:book.BasicDataTable.audioData)
}
inline void BasicDataTable::add_audiodata(const char* value) {
  audiodata_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:book.BasicDataTable.audioData)
}
inline void BasicDataTable::add_audiodata(const void* value, size_t size) {
  audiodata_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:book.BasicDataTable.audioData)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
BasicDataTable::audiodata() const {
  // @@protoc_insertion_point(field_list:book.BasicDataTable.audioData)
  return audiodata_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
BasicDataTable::mutable_audiodata() {
  // @@protoc_insertion_point(field_mutable_list:book.BasicDataTable.audioData)
  return &audiodata_;
}

// -------------------------------------------------------------------

// IndexDataMapTable_IndexDataMapPair

// required int32 index = 1;
inline bool IndexDataMapTable_IndexDataMapPair::has_index() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void IndexDataMapTable_IndexDataMapPair::set_has_index() {
  _has_bits_[0] |= 0x00000001u;
}
inline void IndexDataMapTable_IndexDataMapPair::clear_has_index() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void IndexDataMapTable_IndexDataMapPair::clear_index() {
  index_ = 0;
  clear_has_index();
}
inline ::google::protobuf::int32 IndexDataMapTable_IndexDataMapPair::index() const {
  // @@protoc_insertion_point(field_get:book.IndexDataMapTable.IndexDataMapPair.index)
  return index_;
}
inline void IndexDataMapTable_IndexDataMapPair::set_index(::google::protobuf::int32 value) {
  set_has_index();
  index_ = value;
  // @@protoc_insertion_point(field_set:book.IndexDataMapTable.IndexDataMapPair.index)
}

// required int32 offset = 2;
inline bool IndexDataMapTable_IndexDataMapPair::has_offset() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void IndexDataMapTable_IndexDataMapPair::set_has_offset() {
  _has_bits_[0] |= 0x00000002u;
}
inline void IndexDataMapTable_IndexDataMapPair::clear_has_offset() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void IndexDataMapTable_IndexDataMapPair::clear_offset() {
  offset_ = 0;
  clear_has_offset();
}
inline ::google::protobuf::int32 IndexDataMapTable_IndexDataMapPair::offset() const {
  // @@protoc_insertion_point(field_get:book.IndexDataMapTable.IndexDataMapPair.offset)
  return offset_;
}
inline void IndexDataMapTable_IndexDataMapPair::set_offset(::google::protobuf::int32 value) {
  set_has_offset();
  offset_ = value;
  // @@protoc_insertion_point(field_set:book.IndexDataMapTable.IndexDataMapPair.offset)
}

// -------------------------------------------------------------------

// IndexDataMapTable

// required .book.IndexDataMapTable.IndexDataMapPair indexDataMapPair = 1;
inline bool IndexDataMapTable::has_indexdatamappair() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void IndexDataMapTable::set_has_indexdatamappair() {
  _has_bits_[0] |= 0x00000001u;
}
inline void IndexDataMapTable::clear_has_indexdatamappair() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void IndexDataMapTable::clear_indexdatamappair() {
  if (indexdatamappair_ != NULL) indexdatamappair_->::book::IndexDataMapTable_IndexDataMapPair::Clear();
  clear_has_indexdatamappair();
}
inline const ::book::IndexDataMapTable_IndexDataMapPair& IndexDataMapTable::indexdatamappair() const {
  // @@protoc_insertion_point(field_get:book.IndexDataMapTable.indexDataMapPair)
  return indexdatamappair_ != NULL ? *indexdatamappair_ : *default_instance_->indexdatamappair_;
}
inline ::book::IndexDataMapTable_IndexDataMapPair* IndexDataMapTable::mutable_indexdatamappair() {
  set_has_indexdatamappair();
  if (indexdatamappair_ == NULL) {
    indexdatamappair_ = new ::book::IndexDataMapTable_IndexDataMapPair;
  }
  // @@protoc_insertion_point(field_mutable:book.IndexDataMapTable.indexDataMapPair)
  return indexdatamappair_;
}
inline ::book::IndexDataMapTable_IndexDataMapPair* IndexDataMapTable::release_indexdatamappair() {
  clear_has_indexdatamappair();
  ::book::IndexDataMapTable_IndexDataMapPair* temp = indexdatamappair_;
  indexdatamappair_ = NULL;
  return temp;
}
inline void IndexDataMapTable::set_allocated_indexdatamappair(::book::IndexDataMapTable_IndexDataMapPair* indexdatamappair) {
  delete indexdatamappair_;
  indexdatamappair_ = indexdatamappair;
  if (indexdatamappair) {
    set_has_indexdatamappair();
  } else {
    clear_has_indexdatamappair();
  }
  // @@protoc_insertion_point(field_set_allocated:book.IndexDataMapTable.indexDataMapPair)
}

// -------------------------------------------------------------------

// ModeTable_CodeIndexMapPair

// required int32 code = 1;
inline bool ModeTable_CodeIndexMapPair::has_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ModeTable_CodeIndexMapPair::set_has_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ModeTable_CodeIndexMapPair::clear_has_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ModeTable_CodeIndexMapPair::clear_code() {
  code_ = 0;
  clear_has_code();
}
inline ::google::protobuf::int32 ModeTable_CodeIndexMapPair::code() const {
  // @@protoc_insertion_point(field_get:book.ModeTable.CodeIndexMapPair.code)
  return code_;
}
inline void ModeTable_CodeIndexMapPair::set_code(::google::protobuf::int32 value) {
  set_has_code();
  code_ = value;
  // @@protoc_insertion_point(field_set:book.ModeTable.CodeIndexMapPair.code)
}

// repeated int32 indexList = 2;
inline int ModeTable_CodeIndexMapPair::indexlist_size() const {
  return indexlist_.size();
}
inline void ModeTable_CodeIndexMapPair::clear_indexlist() {
  indexlist_.Clear();
}
inline ::google::protobuf::int32 ModeTable_CodeIndexMapPair::indexlist(int index) const {
  // @@protoc_insertion_point(field_get:book.ModeTable.CodeIndexMapPair.indexList)
  return indexlist_.Get(index);
}
inline void ModeTable_CodeIndexMapPair::set_indexlist(int index, ::google::protobuf::int32 value) {
  indexlist_.Set(index, value);
  // @@protoc_insertion_point(field_set:book.ModeTable.CodeIndexMapPair.indexList)
}
inline void ModeTable_CodeIndexMapPair::add_indexlist(::google::protobuf::int32 value) {
  indexlist_.Add(value);
  // @@protoc_insertion_point(field_add:book.ModeTable.CodeIndexMapPair.indexList)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ModeTable_CodeIndexMapPair::indexlist() const {
  // @@protoc_insertion_point(field_list:book.ModeTable.CodeIndexMapPair.indexList)
  return indexlist_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ModeTable_CodeIndexMapPair::mutable_indexlist() {
  // @@protoc_insertion_point(field_mutable_list:book.ModeTable.CodeIndexMapPair.indexList)
  return &indexlist_;
}

// -------------------------------------------------------------------

// ModeTable

// repeated .book.ModeTable.CodeIndexMapPair codeIndexMapPair = 1;
inline int ModeTable::codeindexmappair_size() const {
  return codeindexmappair_.size();
}
inline void ModeTable::clear_codeindexmappair() {
  codeindexmappair_.Clear();
}
inline const ::book::ModeTable_CodeIndexMapPair& ModeTable::codeindexmappair(int index) const {
  // @@protoc_insertion_point(field_get:book.ModeTable.codeIndexMapPair)
  return codeindexmappair_.Get(index);
}
inline ::book::ModeTable_CodeIndexMapPair* ModeTable::mutable_codeindexmappair(int index) {
  // @@protoc_insertion_point(field_mutable:book.ModeTable.codeIndexMapPair)
  return codeindexmappair_.Mutable(index);
}
inline ::book::ModeTable_CodeIndexMapPair* ModeTable::add_codeindexmappair() {
  // @@protoc_insertion_point(field_add:book.ModeTable.codeIndexMapPair)
  return codeindexmappair_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::book::ModeTable_CodeIndexMapPair >&
ModeTable::codeindexmappair() const {
  // @@protoc_insertion_point(field_list:book.ModeTable.codeIndexMapPair)
  return codeindexmappair_;
}
inline ::google::protobuf::RepeatedPtrField< ::book::ModeTable_CodeIndexMapPair >*
ModeTable::mutable_codeindexmappair() {
  // @@protoc_insertion_point(field_mutable_list:book.ModeTable.codeIndexMapPair)
  return &codeindexmappair_;
}

// -------------------------------------------------------------------

// Node

// required int32 startCode = 1;
inline bool Node::has_startcode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Node::set_has_startcode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Node::clear_has_startcode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Node::clear_startcode() {
  startcode_ = 0;
  clear_has_startcode();
}
inline ::google::protobuf::int32 Node::startcode() const {
  // @@protoc_insertion_point(field_get:book.Node.startCode)
  return startcode_;
}
inline void Node::set_startcode(::google::protobuf::int32 value) {
  set_has_startcode();
  startcode_ = value;
  // @@protoc_insertion_point(field_set:book.Node.startCode)
}

// required int32 endCode = 2;
inline bool Node::has_endcode() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Node::set_has_endcode() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Node::clear_has_endcode() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Node::clear_endcode() {
  endcode_ = 0;
  clear_has_endcode();
}
inline ::google::protobuf::int32 Node::endcode() const {
  // @@protoc_insertion_point(field_get:book.Node.endCode)
  return endcode_;
}
inline void Node::set_endcode(::google::protobuf::int32 value) {
  set_has_endcode();
  endcode_ = value;
  // @@protoc_insertion_point(field_set:book.Node.endCode)
}

// required int32 previous = 3;
inline bool Node::has_previous() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Node::set_has_previous() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Node::clear_has_previous() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Node::clear_previous() {
  previous_ = 0;
  clear_has_previous();
}
inline ::google::protobuf::int32 Node::previous() const {
  // @@protoc_insertion_point(field_get:book.Node.previous)
  return previous_;
}
inline void Node::set_previous(::google::protobuf::int32 value) {
  set_has_previous();
  previous_ = value;
  // @@protoc_insertion_point(field_set:book.Node.previous)
}

// repeated int32 next = 4;
inline int Node::next_size() const {
  return next_.size();
}
inline void Node::clear_next() {
  next_.Clear();
}
inline ::google::protobuf::int32 Node::next(int index) const {
  // @@protoc_insertion_point(field_get:book.Node.next)
  return next_.Get(index);
}
inline void Node::set_next(int index, ::google::protobuf::int32 value) {
  next_.Set(index, value);
  // @@protoc_insertion_point(field_set:book.Node.next)
}
inline void Node::add_next(::google::protobuf::int32 value) {
  next_.Add(value);
  // @@protoc_insertion_point(field_add:book.Node.next)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Node::next() const {
  // @@protoc_insertion_point(field_list:book.Node.next)
  return next_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Node::mutable_next() {
  // @@protoc_insertion_point(field_mutable_list:book.Node.next)
  return &next_;
}

// repeated int32 defaultCode = 5;
inline int Node::defaultcode_size() const {
  return defaultcode_.size();
}
inline void Node::clear_defaultcode() {
  defaultcode_.Clear();
}
inline ::google::protobuf::int32 Node::defaultcode(int index) const {
  // @@protoc_insertion_point(field_get:book.Node.defaultCode)
  return defaultcode_.Get(index);
}
inline void Node::set_defaultcode(int index, ::google::protobuf::int32 value) {
  defaultcode_.Set(index, value);
  // @@protoc_insertion_point(field_set:book.Node.defaultCode)
}
inline void Node::add_defaultcode(::google::protobuf::int32 value) {
  defaultcode_.Add(value);
  // @@protoc_insertion_point(field_add:book.Node.defaultCode)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Node::defaultcode() const {
  // @@protoc_insertion_point(field_list:book.Node.defaultCode)
  return defaultcode_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Node::mutable_defaultcode() {
  // @@protoc_insertion_point(field_mutable_list:book.Node.defaultCode)
  return &defaultcode_;
}

// -------------------------------------------------------------------

// NodeTree

// repeated .book.Node treeNode = 1;
inline int NodeTree::treenode_size() const {
  return treenode_.size();
}
inline void NodeTree::clear_treenode() {
  treenode_.Clear();
}
inline const ::book::Node& NodeTree::treenode(int index) const {
  // @@protoc_insertion_point(field_get:book.NodeTree.treeNode)
  return treenode_.Get(index);
}
inline ::book::Node* NodeTree::mutable_treenode(int index) {
  // @@protoc_insertion_point(field_mutable:book.NodeTree.treeNode)
  return treenode_.Mutable(index);
}
inline ::book::Node* NodeTree::add_treenode() {
  // @@protoc_insertion_point(field_add:book.NodeTree.treeNode)
  return treenode_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::book::Node >&
NodeTree::treenode() const {
  // @@protoc_insertion_point(field_list:book.NodeTree.treeNode)
  return treenode_;
}
inline ::google::protobuf::RepeatedPtrField< ::book::Node >*
NodeTree::mutable_treenode() {
  // @@protoc_insertion_point(field_mutable_list:book.NodeTree.treeNode)
  return &treenode_;
}

// -------------------------------------------------------------------

// book

// required .book.NodeTree nodeTree = 1;
inline bool book::has_nodetree() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void book::set_has_nodetree() {
  _has_bits_[0] |= 0x00000001u;
}
inline void book::clear_has_nodetree() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void book::clear_nodetree() {
  if (nodetree_ != NULL) nodetree_->::book::NodeTree::Clear();
  clear_has_nodetree();
}
inline const ::book::NodeTree& book::nodetree() const {
  // @@protoc_insertion_point(field_get:book.book.nodeTree)
  return nodetree_ != NULL ? *nodetree_ : *default_instance_->nodetree_;
}
inline ::book::NodeTree* book::mutable_nodetree() {
  set_has_nodetree();
  if (nodetree_ == NULL) {
    nodetree_ = new ::book::NodeTree;
  }
  // @@protoc_insertion_point(field_mutable:book.book.nodeTree)
  return nodetree_;
}
inline ::book::NodeTree* book::release_nodetree() {
  clear_has_nodetree();
  ::book::NodeTree* temp = nodetree_;
  nodetree_ = NULL;
  return temp;
}
inline void book::set_allocated_nodetree(::book::NodeTree* nodetree) {
  delete nodetree_;
  nodetree_ = nodetree;
  if (nodetree) {
    set_has_nodetree();
  } else {
    clear_has_nodetree();
  }
  // @@protoc_insertion_point(field_set_allocated:book.book.nodeTree)
}

// repeated .book.ModeTable modeTabelList = 2;
inline int book::modetabellist_size() const {
  return modetabellist_.size();
}
inline void book::clear_modetabellist() {
  modetabellist_.Clear();
}
inline const ::book::ModeTable& book::modetabellist(int index) const {
  // @@protoc_insertion_point(field_get:book.book.modeTabelList)
  return modetabellist_.Get(index);
}
inline ::book::ModeTable* book::mutable_modetabellist(int index) {
  // @@protoc_insertion_point(field_mutable:book.book.modeTabelList)
  return modetabellist_.Mutable(index);
}
inline ::book::ModeTable* book::add_modetabellist() {
  // @@protoc_insertion_point(field_add:book.book.modeTabelList)
  return modetabellist_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::book::ModeTable >&
book::modetabellist() const {
  // @@protoc_insertion_point(field_list:book.book.modeTabelList)
  return modetabellist_;
}
inline ::google::protobuf::RepeatedPtrField< ::book::ModeTable >*
book::mutable_modetabellist() {
  // @@protoc_insertion_point(field_mutable_list:book.book.modeTabelList)
  return &modetabellist_;
}

// required .book.book.ModeType curMode = 3 [default = STUDY];
inline bool book::has_curmode() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void book::set_has_curmode() {
  _has_bits_[0] |= 0x00000004u;
}
inline void book::clear_has_curmode() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void book::clear_curmode() {
  curmode_ = 1;
  clear_has_curmode();
}
inline ::book::book_ModeType book::curmode() const {
  // @@protoc_insertion_point(field_get:book.book.curMode)
  return static_cast< ::book::book_ModeType >(curmode_);
}
inline void book::set_curmode(::book::book_ModeType value) {
  assert(::book::book_ModeType_IsValid(value));
  set_has_curmode();
  curmode_ = value;
  // @@protoc_insertion_point(field_set:book.book.curMode)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace book

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::book::book_ModeType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::book::book_ModeType>() {
  return ::book::book_ModeType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_book_2eproto__INCLUDED
